security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database
            custom_authenticator: App\Security\LoginAuthentificatorAuthenticator
            entry_point: App\Security\LoginAuthentificatorAuthenticator  # Ajout de l'entrée point ici
            logout:
                path: app_logout
                target: app_login

            form_login:
                login_path: app_login
                check_path: app_login
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/boutiquier, roles: ROLE_BOUTIQUIER }


            
        
        
